---
driver:
  name: docker
  hostname: salt-formula.ci.local
  use_sudo: false
  require_chef_omnibus: false

driver_config:
  cap_add:
  - SYS_PTRACE

# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: debian-7
  - name: debian-8
  - name: centos-6
  - name: centos-7

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
#  data_path: test/shared
  is_file_root: false  
  formula: solr
  dependencies: 
    - {name: zookeeper, path: /tmp/zookeeper} 
  pillars:
      top.sls:
        base:
          '*':
            - zookeeper
            - solr
      zookeeper.sls:
        source_url: 'http://www.us.apache.org/dist/zookeeper/zookeeper-3.4.9/zookeeper-3.4.9.tar.gz'
        version: 3.4.9
        # You can disable md5 checking if you know exactly what you are doing and set the following to an empty string.
        source_md5: 3e8506075212c2d41030d874fcc9dcd2
        prefix: /usr/lib
        uid: 6030
        hosts_function: network.get_hostname
        hosts_target: 'roles:zookeeper'
        targeting_method: grain # [compound, glob] also supported
        config:
          data_dir: /var/lib/zookeeper/data
          port: 2181
          jmx_port: 2183
          snap_count: None
          snap_retain_count: 3
          purge_interval: None
          max_client_cnxns: None
          max_perm_size: 128
          max_heap_size: 1024
          initial_heap_size: 256
          jvm_opts: None
          log_level: INFO
          quorum_port: 2888
          election_port: 3888
        restart_on_config: True
      solr.sls:
        solr:
          url: http://www.eu.apache.org/dist/lucene/solr/
          ver: 6.4.1
          name: solr
          logs: /var/solr/logs/
          data: /var/solr/data/
          home: /var/solr/
          java_home: /usr/lib/jvm/java-8-oracle
          user: solr
          install_dir: /opt/solr-6.4.1
          cluster:
            servers:
              solr1:
                ip: 
                id: '1'
              solr2:
                ip: 
                id: '2'
          zoo_url: http://www.eu.apache.org/dist/zookeeper/
          zoo_ver: 3.4.7
          zoo_name: zookeeper
          zoo_logs: /var/zookeeper/logs/
          zoo_data: /var/zookeeper/data/
          zoo_conf_dir: /opt/zookeeper/conf/
          zoo_client_timeout: 30000
          zoo_cluster:
            servers:
              zk1:
                ip: 
                id: '1'
              zk2:
                ip: 
                id: '2'
              zk3:
                ip: 
                id: '3'
          limit:
            soft: 48000
            hard: 64000
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'info' %> 
  state_top:
    base:
      '*':
        - zookeeper
        - zookeeper.server
        - solr
        
suites:
  - name: solr_install
    provisioner:
      state_top:
        base:
          '*':
            - zookeeper
            - zookeeper.server
            - solr
