---
driver:
  name: docker
  hostname: salt-formula.ci.local
  use_sudo: false
  require_chef_omnibus: false

driver_config:
  cap_add:
  - SYS_PTRACE

# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: debian-7
  - name: debian-8
  - name: centos-6
  - name: centos-7

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  data_path: test/shared
  pillars:
      top.sls:
        base:
          '*':
            - solr

      solr.sls:
        solr:
          java_opts:
            - 'Djava.awt.headless=true'
            - 'Xmx128m'
            - 'XX:MaxPermSize=256m'
            - 'XX:+UseConcMarkSweepGC'
          limit:
            soft: 48000
            hard: 64000
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'info' %>
  formula: solr
  state_top:
    base:
      '*':
        - solr
        
suites:
  - name: solr_install
    provisioner:
      state_top:
        base:
          '*':
            - solr