---
driver:
  name: docker
  hostname: salt-formula.ci.local
  use_sudo: false
  require_chef_omnibus: false

driver_config:
  cap_add:
  - SYS_PTRACE

# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: debian-7
  - name: debian-8
  - name: centos-6
  - name: centos-7

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  data_path: test/shared
  pillars:
      top.sls:
        base:
          '*':
            - solr

      solr.sls:
        solr:
          solr_url: http://www.eu.apache.org/dist/lucene/solr/
          solr_ver: 6.3.0
          solr_name: solr
          solr_logs: /var/solr/logs/
          solr_data: /var/solr/data/
          solr_home: /var/solr/
          solr_user: solr
          solr_install_dir: /opt/solr
          solr_cluster:
            servers:
              solr1:
                ip: 
                id: '1'
              solr2:
                ip: 
                id: '2'
          zoo_url: http://www.eu.apache.org/dist/zookeeper/
          zoo_ver: 3.4.7
          zoo_name: zookeeper
          zoo_logs: /var/zookeeper/logs/
          zoo_data: /var/zookeeper/data/
          zoo_conf_dir: /opt/zookeeper/conf/
          zoo_client_timeout: 30000
          zoo_cluster:
            servers:
              zk1:
                ip: 
                id: '1'
              zk2:
                ip: 
                id: '2'
              zk3:
                ip: 
                id: '3'
          java_opts:
            - 'Djava.awt.headless=true'
            - 'Xmx128m'
            - 'XX:MaxPermSize=256m'
            - 'XX:+UseConcMarkSweepGC'
          limit:
            soft: 48000
            hard: 64000
  log_level: <%= ENV['SALT_DEBUG_LEVEL'] || 'info' %>
  formula: solr
  state_top:
    base:
      '*':
        - solr
        
suites:
  - name: solr_install
    provisioner:
      state_top:
        base:
          '*':
            - solr