language: java

rvm:
  - 2.2.5

sudo: required
services: 
  - docker

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

env:
  matrix:
  - INSTANCE: install-ubuntu-1404
  - INSTANCE: install-ubuntu-1604

# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
before_script: 
  - sudo iptables -L DOCKER || sudo iptables -N DOCKER
  - sudo apt-get install git
  - git clone https://github.com/saltstack-formulas/zookeeper-formula.git /tmp/zookeeper

install:
  # setup ci for test formula
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - bundle install

script: bundle exec kitchen verify ${INSTANCE}
